site_name: tesselite/readthedocs
site_url: https://tesselite.github.io/readthedocs
site_author: hello@tesselite.us
site_description: document Tesselite Ltd products usage

nav:
  - home: index.md
  - high-level:
    - content: high-level.md
    - articles:
      - second-ai-revolution: content/second-ai-revolution.md
  - low-level:
    - content: low-level.md
  - usage:
    - relief [geometry]: relief.md
    - routerAI [network]: router_ai.md
  - more [...]:
    - relief:
      - example-1: more/relief-demo1.md
      - example-2: more/relief-demo2.md
      - example-3: more/relief-demo3.md


markdown_extensions:
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'
  - footnotes

plugins:
    - mkdocs-video:
        is_video: True
        video_autoplay: True
        video_muted: True
        video_controls: True
        css_style:
          width: "800px"

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4

  logo: static/images/logo-3.png
  highlightjs: true
  hljs_languages:
    - yaml
  features:
    - navigation.footer
  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk

extra_css:
  - static/css/code-tab.css
  - static/css/image.css